import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/reset.css";
import "../styles/theme.css";
import "./globals.css";
import Header from "@/components/header/header";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const checkTheme = async () => {
  const nextCookies = cookies();
  const themeCookie = nextCookies.get("theme")?.value || "";

  return themeCookie;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await checkTheme();
  return (
    <html lang="en" className="background" data-theme={theme}>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
