import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import "./globals.css";
import NextAuthProvider from "@/providers/next-auth-provider";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import "@fortawesome/fontawesome-svg-core/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const checkTheme = () => {
  const nextCookies = cookies();
  const themeCookie = nextCookies.get("theme")?.value || "";

  return themeCookie;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = checkTheme();
  return (
    <html lang="en" className="background" data-theme={theme}>
      <body className={inter.className}>
        <NextAuthProvider>
          <Header />
          {children}
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
